# Generated by Django 4.0.1 on 2022-01-26 16:11

from django.db import migrations, models
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_comments_options_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=models.ImageField(upload_to=events.models.image_upload),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(upload_to=events.models.image_upload),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_sold',
            field=models.IntegerField(default=0),
        ),
    ]
