# Generated by Django 4.0.1 on 2022-01-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_date_created_event_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='manager',
        ),
    ]
