# Generated by Django 4.0.1 on 2022-01-30 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendeee',
            new_name='attendee',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_event', to='events.event'),
        ),
    ]
