# Generated by Django 4.0.1 on 2022-01-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_attendance_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets_sold',
        ),
    ]
