# Generated by Django 4.0.1 on 2022-01-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_event_tickets_sold_ticket_type_ticket_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type_id',
        ),
        migrations.RemoveField(
            model_name='ticket_type',
            name='event_id',
        ),
    ]
