# Generated by Django 4.0.1 on 2022-01-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('accounts', '0003_remove_comments_event_id_remove_comments_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Ticket_type',
        ),
    ]
