# Generated by Django 4.0.1 on 2022-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_options_alter_favorites_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'System Admin', 'verbose_name_plural': 'System Admins'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EVENT MANAGER', 'Event Manager'), ('CUSTOMER', 'Customer')], default='Super Admin', max_length=13, verbose_name='User Type'),
        ),
    ]
