# Generated by Django 4.0.1 on 2022-01-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_alter_user_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets_sold',
        ),
    ]
