# Generated by Django 4.0.1 on 2022-01-31 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_tickets_sold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_ticketsold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket_type',
            new_name='TicketType',
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name': 'Ticket Typeype', 'verbose_name_plural': 'Ticket Types'},
        ),
        migrations.AddField(
            model_name='ticketsold',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_for_event', to='events.event'),
        ),
        migrations.AddField(
            model_name='ticketsold',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sold_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketsold',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
