# Generated by Django 4.0.1 on 2022-01-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_tickets_sold'),
        ('tickets', '0005_rename_ticket_type_tickettype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number_of_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketsold',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_for_event', to='events.event'),
        ),
        migrations.AlterField(
            model_name='ticketsold',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
