# Generated by Django 4.0.1 on 2022-01-31 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_tickets_sold'),
        ('tickets', '0007_alter_tickettype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsold',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_for_event', to='events.event'),
        ),
    ]
