# Generated by Django 4.0.1 on 2022-01-31 20:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0011_alter_ticket_options_ticket_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bought_by', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ManyToManyField(related_name='type_of_ticket', to='tickets.Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Sold',
                'verbose_name_plural': 'Tickets Sold',
            },
        ),
        migrations.DeleteModel(
            name='TicketSold',
        ),
    ]
