# Generated by Django 4.0.1 on 2022-01-31 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0012_ticketcart_delete_ticketsold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcart',
            options={'verbose_name': 'Ticket Cart', 'verbose_name_plural': 'Tickets Cart'},
        ),
        migrations.RemoveField(
            model_name='ticketcart',
            name='total',
        ),
        migrations.AlterField(
            model_name='ticketcart',
            name='buyer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketcart',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='ticketcart',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticketcart',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_ticket', to='tickets.ticket'),
        ),
    ]
