# Generated by Django 4.0.1 on 2022-01-31 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_tickets_sold'),
        ('tickets', '0014_alter_ticketcart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_worth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_name', models.CharField(max_length=50)),
                ('number_of_coupons', models.PositiveIntegerField(default=0)),
                ('coupon_number', models.CharField(max_length=6)),
                ('apply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_coupon', to='events.event')),
            ],
            options={
                'verbose_name': 'Ticket Coupon',
                'verbose_name_plural': 'Ticket Coupons',
            },
        ),
    ]
