# Generated by Django 4.0.1 on 2022-01-31 21:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticketcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcoupon',
            name='coupon_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), size=None),
        ),
    ]
