# Generated by Django 4.0.1 on 2022-02-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_ticketcoupon_coupon_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcoupon',
            name='coupon_expiry_date',
            field=models.DateTimeField(null=True, verbose_name='Coupon Expiry'),
        ),
        migrations.AddField(
            model_name='ticketcoupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketcoupon',
            name='uses_per_user',
            field=models.PositiveIntegerField(default=1, verbose_name='To Be Used'),
        ),
        migrations.AlterField(
            model_name='ticketcoupon',
            name='coupon_worth',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coupon is Worth'),
        ),
    ]
