# Generated by Django 4.0.1 on 2022-02-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticketcoupon_coupon_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcoupon',
            name='uses_per_user',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
